### ISSUE TITLE
state of bintray?

### ISSUE THREAD

**Issue by ipatch** [ladislas/homebrew-greetings#55]
i'm super new to all of this ie. using CI to setup the auto bottling for homebrew packages, and started working through your guide yesterday, and came across this blog post today?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

does mean an alternative bintray will have to be used for hosting the `.tar.gz` bottles when install a homebrew package from a bottle?

**Comment by ladislas** [comment]
@ipatch I should archive this repo as there is a much better and easier way to setup tap/bottle workflow.

Homebrew has greatly improved support for custom taps' bottles see:

> [Homebrew tap with bottles uploaded to GitHub Releases](https://brew.sh/2020/11/18/homebrew-tap-with-bottles-uploaded-to-github-releases/)

osx-cross/avr now makes full use of this with Github Actions, you can look into [`.github/workflows`](https://github.com/osx-cross/homebrew-avr/tree/master/.github/workflows) for details.

**Comment by ipatch** [comment]
thank you. will look into it, and thanks for sharing. 🙏
